server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus
    username: root
    password: dyzwj

mybatis-plus:
  ##mybatis-plus mapper xml 文件地址
  mapper-locations: classpath*:mapper/*Mapper.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: com.dyzwj.zwjmybatisplus.domain
